// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'most_popular_albums.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

PopularAlbums _$PopularAlbumsFromJson(Map<String, dynamic> json) {
  return PopularAlbums(
    loved: (json['loved'] as List)
        ?.map(
            (e) => e == null ? null : Loved.fromJson(e as Map<String, dynamic>))
        ?.toList(),
  );
}

Map<String, dynamic> _$PopularAlbumsToJson(PopularAlbums instance) =>
    <String, dynamic>{
      'loved': instance.loved,
    };

Loved _$LovedFromJson(Map<String, dynamic> json) {
  return Loved(
    idAlbum: json['idAlbum'] as String,
    idArtist: json['idArtist'] as String,
    idLabel: json['idLabel'] as String,
    strAlbum: json['strAlbum'] as String,
    strAlbumStripped: json['strAlbumStripped'] as String,
    strArtist: json['strArtist'] as String,
    strArtistStripped: json['strArtistStripped'] as String,
    intYearReleased: json['intYearReleased'] as String,
    strStyle: json['strStyle'] as String,
    strGenre: json['strGenre'] as String,
    strLabel: json['strLabel'] as String,
    strReleaseFormat: json['strReleaseFormat'] as String,
    intSales: json['intSales'] as String,
    strAlbumThumb: json['strAlbumThumb'] as String,
    strAlbumThumbHQ: json['strAlbumThumbHQ'] as String,
    strAlbumThumbBack: json['strAlbumThumbBack'] as String,
    strAlbumCDart: json['strAlbumCDart'] as String,
    strAlbumSpine: json['strAlbumSpine'] as String,
    strAlbum3DCase: json['strAlbum3DCase'] as String,
    strAlbum3DFlat: json['strAlbum3DFlat'] as String,
    strAlbum3DFace: json['strAlbum3DFace'] as String,
    strAlbum3DThumb: json['strAlbum3DThumb'] as String,
    strDescription: json['strDescription'] as String,
    strDescriptionDE: json['strDescriptionDE'] as String,
    strDescriptionFR: json['strDescriptionFR'] as String,
    strDescriptionCN: json['strDescriptionCN'] as String,
    strDescriptionIT: json['strDescriptionIT'] as String,
    strDescriptionJP: json['strDescriptionJP'] as String,
    strDescriptionRU: json['strDescriptionRU'] as String,
    strDescriptionES: json['strDescriptionES'] as String,
    strDescriptionPT: json['strDescriptionPT'] as String,
    strDescriptionSE: json['strDescriptionSE'] as String,
    strDescriptionNL: json['strDescriptionNL'] as String,
    strDescriptionHU: json['strDescriptionHU'] as String,
    strDescriptionNO: json['strDescriptionNO'] as String,
    strDescriptionIL: json['strDescriptionIL'] as String,
    strDescriptionPL: json['strDescriptionPL'] as String,
    intLoved: json['intLoved'] as String,
    intScore: json['intScore'] as String,
    intScoreVotes: json['intScoreVotes'] as String,
    strReview: json['strReview'] as String,
    strMood: json['strMood'] as String,
    strTheme: json['strTheme'] as String,
    strSpeed: json['strSpeed'] as String,
    strLocation: json['strLocation'] as String,
    strMusicBrainzID: json['strMusicBrainzID'] as String,
    strMusicBrainzArtistID: json['strMusicBrainzArtistID'] as String,
    strAllMusicID: json['strAllMusicID'] as String,
    strBBCReviewID: json['strBBCReviewID'] as String,
    strRateYourMusicID: json['strRateYourMusicID'] as String,
    strDiscogsID: json['strDiscogsID'] as String,
    strWikidataID: json['strWikidataID'] as String,
    strWikipediaID: json['strWikipediaID'] as String,
    strGeniusID: json['strGeniusID'] as String,
    strLyricWikiID: json['strLyricWikiID'] as String,
    strMusicMozID: json['strMusicMozID'] as String,
    strItunesID: json['strItunesID'] as String,
    strAmazonID: json['strAmazonID'] as String,
    strLocked: json['strLocked'] as String,
  );
}

Map<String, dynamic> _$LovedToJson(Loved instance) => <String, dynamic>{
      'idAlbum': instance.idAlbum,
      'idArtist': instance.idArtist,
      'idLabel': instance.idLabel,
      'strAlbum': instance.strAlbum,
      'strAlbumStripped': instance.strAlbumStripped,
      'strArtist': instance.strArtist,
      'strArtistStripped': instance.strArtistStripped,
      'intYearReleased': instance.intYearReleased,
      'strStyle': instance.strStyle,
      'strGenre': instance.strGenre,
      'strLabel': instance.strLabel,
      'strReleaseFormat': instance.strReleaseFormat,
      'intSales': instance.intSales,
      'strAlbumThumb': instance.strAlbumThumb,
      'strAlbumThumbHQ': instance.strAlbumThumbHQ,
      'strAlbumThumbBack': instance.strAlbumThumbBack,
      'strAlbumCDart': instance.strAlbumCDart,
      'strAlbumSpine': instance.strAlbumSpine,
      'strAlbum3DCase': instance.strAlbum3DCase,
      'strAlbum3DFlat': instance.strAlbum3DFlat,
      'strAlbum3DFace': instance.strAlbum3DFace,
      'strAlbum3DThumb': instance.strAlbum3DThumb,
      'strDescription': instance.strDescription,
      'strDescriptionDE': instance.strDescriptionDE,
      'strDescriptionFR': instance.strDescriptionFR,
      'strDescriptionCN': instance.strDescriptionCN,
      'strDescriptionIT': instance.strDescriptionIT,
      'strDescriptionJP': instance.strDescriptionJP,
      'strDescriptionRU': instance.strDescriptionRU,
      'strDescriptionES': instance.strDescriptionES,
      'strDescriptionPT': instance.strDescriptionPT,
      'strDescriptionSE': instance.strDescriptionSE,
      'strDescriptionNL': instance.strDescriptionNL,
      'strDescriptionHU': instance.strDescriptionHU,
      'strDescriptionNO': instance.strDescriptionNO,
      'strDescriptionIL': instance.strDescriptionIL,
      'strDescriptionPL': instance.strDescriptionPL,
      'intLoved': instance.intLoved,
      'intScore': instance.intScore,
      'intScoreVotes': instance.intScoreVotes,
      'strReview': instance.strReview,
      'strMood': instance.strMood,
      'strTheme': instance.strTheme,
      'strSpeed': instance.strSpeed,
      'strLocation': instance.strLocation,
      'strMusicBrainzID': instance.strMusicBrainzID,
      'strMusicBrainzArtistID': instance.strMusicBrainzArtistID,
      'strAllMusicID': instance.strAllMusicID,
      'strBBCReviewID': instance.strBBCReviewID,
      'strRateYourMusicID': instance.strRateYourMusicID,
      'strDiscogsID': instance.strDiscogsID,
      'strWikidataID': instance.strWikidataID,
      'strWikipediaID': instance.strWikipediaID,
      'strGeniusID': instance.strGeniusID,
      'strLyricWikiID': instance.strLyricWikiID,
      'strMusicMozID': instance.strMusicMozID,
      'strItunesID': instance.strItunesID,
      'strAmazonID': instance.strAmazonID,
      'strLocked': instance.strLocked,
    };
